"""The direct queries: a thread's pages, opening a thread, the inbox listing and its next pages,
the message requests, a folder's unread rows, and a text send and its unsend.
"""

from __future__ import annotations

from dumpstagram._private.web.documents.common import PersistedQuery

__all__ = [
   "DIRECT_INBOX",
   "DIRECT_INBOX_NEXT_PAGE",
   "DIRECT_TEXT_SEND",
   "DIRECT_UNSEND",
   "FOLDER_UNREAD_ROWS",
   "MESSAGE_REQUESTS",
   "THREAD_DETAIL",
   "THREAD_MESSAGE_PAGE",
   "THREAD_OLDER_PAGE",
]

THREAD_MESSAGE_PAGE = PersistedQuery(
   doc_id="27502152406082940",
   friendly_name="useIGDMessageListPaginationQuery",
   finding_id="direct-thread-message-page",
)
"""One page of messages in one direct thread, 20 edges, capped server side.

Observed live on 2026-09-20 and again on 2026-09-21.
"""

THREAD_DETAIL = PersistedQuery(
   doc_id="28730473946590056",
   friendly_name="IGDThreadDetailQuery",
   finding_id="open-a-direct-thread",
)
"""What a browser sends to open a thread: the thread, with its newest 20 messages.

The messages are the same 28-key nodes :data:`THREAD_OLDER_PAGE` returns, under a different
root field, and the connection's ``end_cursor`` is what the browser's first older page sends
as ``after``.

Observed on two cold loads of a thread on 2026-09-23 and replayed twice the same day.
"""

THREAD_OLDER_PAGE = PersistedQuery(
   doc_id="28079551424999855",
   friendly_name="IGDMessageListOffMsysQuery",
   finding_id="direct-thread-older-page-offmsys",
)
"""What a browser sends for each older page of a thread as it scrolls up.

The same variables and root field as :data:`THREAD_MESSAGE_PAGE`, under a new name and id. On
2026-09-23 a browser sent this one twelve times across two captures and the old one never,
while the old one still answered a replay the same day.
"""

DIRECT_INBOX = PersistedQuery(
   doc_id="28794932076791671",
   friendly_name="PolarisDirectInboxQuery",
   finding_id="direct-inbox-thread-list",
)
"""The direct inbox's first page of threads, newest activity first, as an inbox load reads it.

Each row carries ``last_activity_timestamp_ms`` and its newest five messages, which is what a
poll compares. It takes no argument but the document's iris device id, and the next page goes
through another query whose id has not been observed. The notes tray is not in it.

Verified by two browser loads and a page replay on 2026-09-23, and by two engine reads 60 s
apart the same night, under ruling 23, which found every row identical with nothing done
between them. What a new message does to a row has not been observed yet.
"""

DIRECT_INBOX_NEXT_PAGE = PersistedQuery(
   doc_id="28000787896268887",
   friendly_name="IGDThreadListOffMsysPaginationQuery",
   finding_id="direct-inbox-thread-list-next-page",
)
"""Every inbox page after the first, keyed on the mailbox id and the previous page's cursor.

It answers under ``fetch__SlideMailbox`` with rows of the same 26 keys the first page carries.
The mailbox id is the ``id`` every mailbox root carries, equal to the viewer's messaging id.
Replayed twice by the engine on 2026-09-24 with a page size of 15, the first page's compiled
size and not a value any browser was seen sending, and both answers listed the same 15 threads,
none of them on the first page.
"""

MESSAGE_REQUESTS = PersistedQuery(
   doc_id="27525641663781745",
   friendly_name="IGDMessageRequestLeftRailStandaloneQuery",
   finding_id="direct-message-requests",
)
"""The pending and spam request folders, one page of each, as the requests view reads them.

It answers under two roots, ``pendingMailbox`` and ``spamMailbox``. Replayed twice by the engine
on 2026-09-24, when both folders were empty, so a row in either has not been observed.
"""

FOLDER_UNREAD_ROWS = PersistedQuery(
   doc_id="27437959689223570",
   friendly_name="useIGDSystemFolderUnreadThreadCountQuery",
   finding_id="direct-inbox-unread-thread-count",
)
"""The rows a folder's unread count is taken over, sent for the inbox and then for the pending
requests in every inbox load.

Each row carries its last activity, its read receipts and the marked unread and muted flags, and
no count: the browser counts. Seen in two inbox loads and replayed on 2026-09-23, and replayed by
the engine for the pending folder on 2026-09-24.
"""

DIRECT_TEXT_SEND = PersistedQuery(
   doc_id="26911679871773184",
   friendly_name="IGDirectTextSendMutation",
   finding_id="send-a-direct-text-message",
)
"""Send one text message into one direct thread, fourteen variables, none wrapped in ``input``.

``ig_thread_igid`` takes the thread's ``thread_fbid``, not its ``thread_key`` and not its
39-digit ``thread_id``, and ``offline_threading_id`` is generated by the client. The answer
carries the new message's ``message_id`` (``id`` equal to it) and ``timestamp_ms``, and a thread
read echoes the ``offline_threading_id`` on the message node. Observed once from the browser's
composer and once from an engine send on 2026-09-23, each unsent in the same run.
"""

DIRECT_UNSEND = PersistedQuery(
   doc_id="26948700068153789",
   friendly_name="IGDMessageUnsendDialogOffMsysMutation",
   finding_id="unsend-a-direct-message",
)
"""Unsend one of the viewer's own direct messages.

It takes the message id and the thread's 39-digit ``thread_id`` under ``send_data``, which is
neither of the two ids the thread reads are keyed on, and answers ``direct_unsend_message``
true. Observed once from the browser's message menu and once from an engine send on
2026-09-23. The unsent message was absent from the next thread read, with no placeholder.
"""
